### ISSUE TITLE
openstack images not found 

### ISSUE THREAD

**Issue by sinu** [mistio/mist-ce#952]
openstack images are not listing , do you know why ?
![image](https://user-images.githubusercontent.com/1231202/54083195-79b22300-4346-11e9-8a86-92469d8ab1a2.png)

**Comment by d-mo** [comment]
Please try out with the latest release (v4.0.3). The issue has been fixed.

**Comment by sinu** [comment]
still the same issue .is there any way to specify glance api ?

**Comment by sinu** [comment]
Can you tell me if there is any way to skip ssl validation for openstack api

**Comment by d-mo** [comment]
Please try accessing the `/api/v1/clouds/ID/images` path in your browser, replacing ID with the id of your OpenStack cloud within Mist. Also, before hitting the above URL, you can try tailing the api log to look for errors.
`docker-compose logs -f --tail 1 api`
Let me know about the result.

It's not currently possible to override the glance api URL through Mist. However, Libcloud does provide such an option. If you feel like digging deeper, connect to the api container and hardcode your glance api url within the OpenStack Libcloud driver.
```
docker-compose exec api sh
```
```
sed -i "s/get('ex_force_image_url')/get('ex_force_image_url','URI')/g"  libcloud/
libcloud/compute/drivers/openstack.py
pkill -HUP uwsgi
exit
```
Replace URI in the above commands with the actual Glance API URI. Then retry the previous experiment to see if this fixes things. If you now see a valid response in the `/api/v1/clouds/ID/images` request, you'll just need to apply the same patch to the celery-prefork container for everything to work properly. 
```
docker-compose exec celery-prefork sed -i "s/get('ex_force_image_url')/get('ex_force_image_url','URI')/g"  libcloud/
libcloud/compute/drivers/openstack.py
```
```
exit
```

**Comment by d-mo** [comment]
Regarding SSL validation, you can configure the host names whose TLS certificates shouldn't be verified, by setting NO_VERIFY_HOSTS in settings/settings.py, e.g.
```
NO_VERIFY_HOSTS = ['192.168.12.14', 'selfsignedcert.me']
```
Restart api & celery-prefork for the changes to take effect.
```
docker-compose restart api celery-prefork
```

**Comment by sinu** [comment]
> docker-compose restart api celery-prefork

@d-mo 

pi_1                   | 2019-03-21 12:22:44,859 INFO  [mist.api.clouds.methods][uWSGIWorker6Core0] Adding new cloud in provider 'openstack'
api_1                   | 2019-03-21 12:22:44,861 WARNI [mist.api.helpers][uWSGIWorker6Core0] Got param 'auth_url' when expecting 'url', transforming.
api_1                   | 2019-03-21 12:22:44,861 WARNI [mist.api.helpers][uWSGIWorker6Core0] Got param 'tenant_name' when expecting 'tenant', transforming.
api_1                   | 2019-03-21 12:22:44,900 ERROR [mist.api.clouds.controllers.compute.base][uWSGIWorker6Core0] SSLError on running list_nodes on <class 'mist.api.clouds.models.OpenStackCloud'> cloud OpenStack (0dfbc05501ac4235ab4304394cdfae06) of Org admin@example.com (1 teams - 1 members): HTTPSConnectionPool(host='mymistce.example.com', port=5000): Max retries exceeded with url: /v3 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
api_1                   | 2019-03-21 12:22:44,905 ERROR [mist.api.clouds.controllers.main.base][uWSGIWorker6Core0] Will not update cloud <class 'mist.api.clouds.models.OpenStackCloud'> cloud OpenStack (0dfbc05501ac4235ab4304394cdfae06) of Org admin@example.com (1 teams - 1 members) because we couldn't connect: SSLError('SSL certificate verification error with host')
api_1                   | 2019-03-21 12:22:44,905 INFO  [mist.api.views][uWSGIWorker6Core0] MistError: SSLError('SSL certificate verification error with host')
api_1                   | [pid: 62|app: 0|req: 1/3] 172.18.0.27 () {44 vars in 833 bytes} [Thu Mar 21 12:22:44 2019] POST /api/v1/clouds => generated 44 bytes in 84 msecs (HTTP/1.0 500) 2 headers in 98 bytes (1 switches on core 0)
api_1                   | 2019-03-21 12:22:45,969 INFO  [mist.api.clouds.methods][uWSGIWorker7Core0] Adding new cloud in provider 'openstack'
api_1                   | 2019-03-21 12:22:45,972 WARNI [mist.api.helpers][uWSGIWorker7Core0] Got param 'auth_url' when expecting 'url', transforming.
api_1                   | 2019-03-21 12:22:45,972 WARNI [mist.api.helpers][uWSGIWorker7Core0] Got param 'tenant_name' when expecting 'tenant', transforming.
api_1                   | 2019-03-21 12:22:46,011 ERROR [mist.api.clouds.controllers.compute.base][uWSGIWorker7Core0] SSLError on running list_nodes on <class 'mist.api.clouds.models.OpenStackCloud'> cloud OpenStack (0b0d677572f54acb93e0f014f1054720) of Org admin@example.com (1 teams - 1 members): HTTPSConnectionPool(host='mymistce.example.com', port=5000): Max retries exceeded with url: /v3 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
api_1                   | 2019-03-21 12:22:46,017 ERROR [mist.api.clouds.controllers.main.base][uWSGIWorker7Core0] Will not update cloud <class 'mist.api.clouds.models.OpenStackCloud'> cloud OpenStack (0b0d677572f54acb93e0f014f1054720) of Org admin@example.com (1 teams - 1 members) because we couldn't connect: SSLError('SSL certificate verification error with host')
api_1                   | 2019-03-21 12:22:46,017 INFO  [mist.api.views][uWSGIWorker7Core0] MistError: SSLError('SSL certificate verification error with host')
api_1                   | [pid: 64|app: 0|req: 1/4] 172.18.0.27 () {44 vars in 833 bytes} [Thu Mar 21 12:22:45 2019] POST /api/v1/clouds => generated 44 bytes in 84 msecs (HTTP/1.0 500) 2 headers in 98 bytes (1 switches on core 0)
api_1                   | 2019-03-21 12:22:46,689 INFO  [mist.api.clouds.methods][uWSGIWorker8Core0] Adding new cloud in provider 'openstack'
api_1                   | 2019-03-21 12:22:46,691 WARNI [mist.api.helpers][uWSGIWorker8Core0] Got param 'auth_url' when expecting 'url', transforming.
api_1                   | 2019-03-21 12:22:46,691 WARNI [mist.api.helpers][uWSGIWorker8Core0] Got param 'tenant_name' when expecting 'tenant', transforming.
api_1                   | 2019-03-21 12:22:46,736 ERROR [mist.api.clouds.controllers.compute.base][uWSGIWorker8Core0] SSLError on running list_nodes on <class 'mist.api.clouds.models.OpenStackCloud'> cloud OpenStack (cc72e0bfdce4444c9aa5eec49f713216) of Org admin@example.com (1 teams - 1 members): HTTPSConnectionPool(host='mymistce.example.com', port=5000): Max retries exceeded with url: /v3 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
api_1                   | 2019-03-21 12:22:46,741 ERROR [mist.api.clouds.controllers.main.base][uWSGIWorker8Core0] Will not update cloud <class 'mist.api.clouds.models.OpenStackCloud'> cloud OpenStack (cc72e0bfdce4444c9aa5eec49f713216) of Org admin@example.com (1 teams - 1 members) because we couldn't connect: SSLError('SSL certificate verification error with host')
api_1                   | 2019-03-21 12:22:46,742 INFO  [mist.api.views][uWSGIWorker8Core0] MistError: SSLError('SSL certificate verification error with host')
api_1                   | [pid: 65|app: 0|req: 1/5] 172.18.0.27 () {44 vars in 833 bytes} [Thu Mar 21 12:22:46 2019] POST /api/v1/clouds => generated 44 bytes in 91 msecs (HTTP/1.0 500) 2 headers in 98 bytes (1 switches on core 0)

**Comment by d-mo** [comment]
Try adding the following in settings/settings.py
```
NO_VERIFY_HOSTS = ['mymistce.example.com']
```
And restart
```
docker-compose restart api celery-prefork
```

**Comment by sinu** [comment]
> 
> 
> Try adding the following in settings/settings.py
> 
> ```
> NO_VERIFY_HOSTS = ['mymistce.example.com']
> ```
> 
> And restart
> 
> ```
> docker-compose restart api celery-prefork
> ```

@d-mo still not working

**Comment by d-mo** [comment]
Still failing with SSL errors? That's weird. You could try disabling SSL verification altogether in libcloud. Add the following in settings/settings.py and restart
```
import libcloud.security
libcloud.security.VERIFY_SSL_CERT=False
```

**Comment by sinu** [comment]
@d-mo now the error changed

api_1                   | 2019-03-22 02:11:00,281 INFO  [mist.api.clouds.methods][uWSGIWorker5Core0] Adding new cloud in provider 'openstack'
api_1                   | 2019-03-22 02:11:00,283 WARNI [mist.api.helpers][uWSGIWorker5Core0] Got param 'auth_url' when expecting 'url', transforming.
api_1                   | 2019-03-22 02:11:00,283 WARNI [mist.api.helpers][uWSGIWorker5Core0] Got param 'tenant_name' when expecting 'tenant', transforming.
api_1                   | 2019-03-22 02:11:00,292 ERROR [mist.api.clouds.controllers.compute.base][uWSGIWorker5Core0] Error while running list_nodes on <class 'mist.api.clouds.models.OpenStackCloud'> cloud OpenStack (43df3a95662b4e7bbbaf72ed9be90b9a) of Org admin@example.com (1 teams - 1 members)
api_1                   | Traceback (most recent call last):
api_1                   |   File "/mist.api/src/mist/api/clouds/controllers/compute/base.py", line 271, in _list_machines
api_1                   |     nodes = self._list_machines__fetch_machines()
api_1                   |   File "/mist.api/src/mist/api/clouds/controllers/compute/base.py", line 548, in _list_machines__fetch_machines
api_1                   |     return self.connection.list_nodes()
api_1                   |   File "/mist.api/libcloud/libcloud/compute/drivers/openstack.py", line 191, in list_nodes
api_1                   |     self.connection.request('/servers/detail', params=params).object)
api_1                   |   File "/mist.api/libcloud/libcloud/common/openstack.py", line 226, in request
api_1                   |     raw=raw)
api_1                   |   File "/mist.api/libcloud/libcloud/common/base.py", line 535, in request
api_1                   |     action = self.morph_action_hook(action)
api_1                   |   File "/mist.api/libcloud/libcloud/common/openstack.py", line 293, in morph_action_hook
api_1                   |     self._populate_hosts_and_request_paths()
api_1                   |   File "/mist.api/libcloud/libcloud/common/openstack.py", line 327, in _populate_hosts_and_request_paths
api_1                   |     osa = osa.authenticate(**kwargs)  # may throw InvalidCreds
api_1                   |   File "/mist.api/libcloud/libcloud/common/openstack_identity.py", line 855, in authenticate
api_1                   |     return self._authenticate_2_0_with_password()
api_1                   |   File "/mist.api/libcloud/libcloud/common/openstack_identity.py", line 880, in _authenticate_2_0_with_password
api_1                   |     return self._authenticate_2_0_with_body(reqbody)
api_1                   |   File "/mist.api/libcloud/libcloud/common/openstack_identity.py", line 885, in _authenticate_2_0_with_body
api_1                   |     method='POST')
api_1                   |   File "/mist.api/libcloud/libcloud/common/base.py", line 637, in request
api_1                   |     response = responseCls(**kwargs)
api_1                   |   File "/mist.api/libcloud/libcloud/common/base.py", line 153, in __init__
api_1                   |     headers=self.headers)
api_1                   | libcloud.common.exceptions.BaseHTTPError: {"error": {"message": "get_version_v3() got an unexpected keyword argument 'auth'", "code": 400, "title": "Bad Request"}}
api_1                   | 2019-03-22 02:11:00,296 ERROR [mist.api.clouds.controllers.main.base][uWSGIWorker5Core0] Will not update cloud <class 'mist.api.clouds.models.OpenStackCloud'> cloud OpenStack (43df3a95662b4e7bbbaf72ed9be90b9a) of Org admin@example.com (1 teams - 1 members) because we couldn't connect: CloudUnavailableError('Cloud unavailable')
api_1                   | 2019-03-22 02:11:00,302 INFO  [mist.api.views][uWSGIWorker5Core0] MistError: CloudUnavailableError('Cloud unavailable')
api_1                   | [pid: 78|app: 0|req: 21/51] 172.18.0.27 () {44 vars in 833 bytes} [Fri Mar 22 02:11:00 2019] POST /api/v1/clouds => generated 17 bytes in 36 msecs (HTTP/1.0 503) 2 headers in 96 bytes (1 switches on core 0)

**Comment by d-mo** [comment]
What version of OpenStack are you running? Looks like it only supports v3 auth. Mist is forcing v2 auth but this shouldn't be necessary since Libcloud supports v3 for some time now. You can try patching this with the following commands:
```
docker-compose exec api sed -i 's/2.0_password/3.x_password/g' /mist.api/src/mist/api/clouds/controllers/compute/controllers.py
docker-compose exec celery-prefork sed -i 's/2.0_password/3.x_password/g' /mist.api/src/mist/api/clouds/controllers/compute/controllers.py
docker-compose restart api celery-prefork
```
If that works for you we'll include the above patch in the next release.

**Comment by d-mo** [comment]
Fixed in v4.1.0
